apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels:
    app: test2
    scv/number: "1"
spec:
  schedulerName: yoda-scheduler
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80

