apiVersion: v1
kind: Pod
metadata:
  name: test1
  labels:
    app: test1
    scv/number: "2"
spec:
  schedulerName: yoda-scheduler2
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80