apiVersion: v1
kind: Pod
metadata:
  name: test1
  labels:
    app: test1
    scv/clock: "5705"
    scv/memory: "8000"
spec:
  schedulerName: yoda-scheduler
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80

